version = 0.1
[default.deploy.parameters]
stack_name = "tesina-migration-scenario-io-stack"
resolve_s3 = true
s3_prefix = "tesina-migration-scenario-io-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
